### ISSUE TITLE
Inference guidance

### ISSUE THREAD

**Issue by MonolithFoundation** [nttcslab-sp/mamba-diarization#4]
Hi, tutorial only contains training setup, how to inference on the trained model with a multi speaker audio as input?

**Comment by FrenchKrab** [comment]
This is in my TODO list, but you can do something like:
```python
you_mamba_based_model = SdResBlocks(blocks=YOUR_CONFIG, wav2vec='WAVLM_BASE_PLUS')
pipeline = SpeakerDiarizationPipeline(
    segmentation=you_mamba_based_model,
    embedding="speechbrain/spkrec-ecapa-voxceleb",
    embedding_exclude_overlap=True,
    clustering="AgglomerativeClustering",
)
# instantiate the parameters and do the inference like in the existing tutorials
```

So in short, just follow the [pyannote audio documentation / tutorial notebooks](https://github.com/pyannote/pyannote-audio/tree/develop?tab=readme-ov-file#documentation) (and use the segmentation model proposed in this repository instead of PyanNet). You can also check out https://github.com/FrenchKrab/IS2023-powerset-diarization which also only changes the segmentation model of the pipeline (and from which i pulled that example code snippet from).

We do not change any of the pipeline logic in this repository/paper, if something is unclear for this part, the answer is most likely in a pyannote.audio paper/tutorial/issue !

**Comment by MonolithFoundation** [comment]
Hi, in my humble opinion, pyannote can be use out of box with a model url from huggingface.

Would u also try using pyannote with your custom hf model url? it should be very convenient.

Crrently, we can not get the mamba model from your repo

**Comment by FrenchKrab** [comment]
Sorry, no plan for model checkpoint release.

**Comment by MonolithFoundation** [comment]
Wholy...
