### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by KeystoneScience** [nttcslab-sp/mamba-diarization#8]
Hello! Not an issue with the code base, but I am very interested in learning more about this. I read your paper, and I was wondering if you had anywhere that explains your motivation behind some of the structure around the Mamba blocks – I know mamba is just inserted in replacement of the BiLSTM block, but if you could point me to where I could learn more about some of the motivating principles that would be amazing.

**Comment by FrenchKrab** [comment]
Hello, thanks for the question!
There's no new block architecture in the paper but I can point to 

For how the internals of the Mamba block work (both the block architecture and SSM part), the [original mamba paper](https://arxiv.org/abs/2312.00752) probably explains it best. But reading this paper first is a lot to take in, so you can also read the S4 paper first or a [video presentation of it by one of the author](https://youtu.be/luCBXCErkCs?si=bFP7nxqG60mkqsUb) which does a great job at giving an intuition of what's going on.

For the bidirectionality, it's very simple: RNN blocks with memory can only reason on the past, which is very limiting. Bidirectional LSTM / Mamba / anything is a way to combine both past and future 'memory' of the sequence so that the model has access to more information. In our paper, we use the '[External Bidirectional Mamba](https://arxiv.org/abs/2405.12609)' because experimentally it worked best.
